---
abstract: 'Review Board Basic Bot IRC plugin'
author:
  - 'Daniel Lukasiak'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bot-BasicBot-Pluggable-Module-ReviewBoard
requires:
  Bot::BasicBot::Pluggable::Module: 0
  JSON: 0
  LWP::Simple: 0
  base: 0
  perl: 5.010
  strict: 0
  warnings: 0
version: 1.0.1
